--!strict
-- ModuleScript: StarterPlayer/StarterPlayerScripts/Controllers/CharacterAnimationController
local Players=game:GetService("Players"); local RunService=game:GetService("RunService"); local RS=game:GetService("ReplicatedStorage")
local Config:any=require(RS:WaitForChild("Shared"):WaitForChild("AnimationConfig")); local C={}; C.__index=C
local LocalPlayer=Players.LocalPlayer :: Player
function C.new():any return setmetatable({Tracks={},Current=nil,Character=nil,Humanoid=nil,Animator=nil,Connections={},StepConnection=nil},C) end
function C._cleanup(self:any) for _,connection:RBXScriptConnection in self.Connections do connection:Disconnect() end; table.clear(self.Connections); for _,track:AnimationTrack in self.Tracks do track:Stop(0); track:Destroy() end; table.clear(self.Tracks); self.Current=nil; self.Character=nil; self.Humanoid=nil; self.Animator=nil end
function C._load(self:any,character:Model) self:_cleanup(); self.Character=character; local h=character:WaitForChild("Humanoid",10); if not h or not h:IsA("Humanoid") then return end; self.Humanoid=h; local animator=h:WaitForChild("Animator",10); if not animator or not animator:IsA("Animator") then return end; self.Animator=animator; local animate=character:FindFirstChild("Animate"); if animate and (animate:IsA("LocalScript") or animate:IsA("Script")) then animate.Disabled=true end; for key:string,def:any in Config.Animations do if def.Id~="rbxassetid://0" then local a=Instance.new("Animation"); a.Name=key; a.AnimationId=def.Id; local track=animator:LoadAnimation(a); a:Destroy(); track.Priority=def.Priority; track.Looped=def.Looped; self.Tracks[key]=track end end; self:_transition("Idle") end
function C._transition(self:any,key:string) if self.Current==key then return end; local old:AnimationTrack?=if self.Current then self.Tracks[self.Current] else nil; if old then old:Stop(Config.FadeOut) end; self.Current=key; local track:AnimationTrack?=self.Tracks[key]; if track then track:Play(Config.FadeIn) end end
function C.PlayAction(self:any,key:string):AnimationTrack? local def:any=Config.Animations[key]; local track:AnimationTrack?=self.Tracks[key]; if not def or not track then return nil end; track:Play(Config.FadeIn); return track end
function C._step(self:any) local h:Humanoid?=self.Humanoid; if not h or h.Health<=0 then return end; local state=h:GetState(); local key:string; if state==Enum.HumanoidStateType.Jumping then key="Jump" elseif state==Enum.HumanoidStateType.Freefall then key="Fall" else local character:Model?=self.Character; local root=if character then character:FindFirstChild("HumanoidRootPart") else nil; local velocity=if root and root:IsA("BasePart") then root.AssemblyLinearVelocity else Vector3.zero; local speed=Vector3.new(velocity.X,0,velocity.Z).Magnitude; local crouched=h:GetAttribute("Crouched")==true; if crouched then key=if speed<.5 then "CrouchIdle" else "CrouchWalk" elseif speed<.5 then key="Idle" elseif speed>13 then key="Run" else key="Walk" end; self:_transition(key); local track:AnimationTrack?=self.Tracks[key]; local def:any=Config.Animations[key]; if track and def and def.AuthoredSpeed>1 then track:AdjustSpeed(math.clamp(speed/def.AuthoredSpeed,Config.MinSpeed,Config.MaxSpeed)) end end end
function C.Start(self:any) LocalPlayer.CharacterAdded:Connect(function(ch) self:_load(ch) end); LocalPlayer.CharacterRemoving:Connect(function() self:_cleanup() end); if LocalPlayer.Character then self:_load(LocalPlayer.Character) end; self.StepConnection=RunService.Heartbeat:Connect(function() self:_step() end) end
return C
