--!strict
-- ModuleScript: ServerScriptService/Services/CharacterService
local Players=game:GetService("Players"); local RS=game:GetService("ReplicatedStorage")
local Config:any=require(RS:WaitForChild("Shared"):WaitForChild("CharacterConfig"))
local Service={}; Service.__index=Service
function Service.new(states:any,remote:RemoteEvent,onCancel:(Player, string)->()):any return setmetatable({States=states,Remote=remote,OnCancel=onCancel,Connections={} :: {[Player]:{RBXScriptConnection}},BoundCharacters={} :: {[Player]:Model}},Service) end
function Service._character(self:any,player:Player,character:Model) if self.BoundCharacters[player]==character then return end; self.BoundCharacters[player]=character; local h=character:WaitForChild("Humanoid",10); local root=character:WaitForChild("HumanoidRootPart",10); if not h or not h:IsA("Humanoid") or not root or not root:IsA("BasePart") or h.RigType~=Enum.HumanoidRigType.R15 then if h and h:IsA("Humanoid") then h.Health=0 else character:Destroy() end; return end; local animator=h:FindFirstChildOfClass("Animator"); if not animator then animator=Instance.new("Animator"); animator.Parent=h end; h.UseJumpPower=Config.UseJumpPower; h.WalkSpeed=Config.WalkSpeed; h.JumpPower=Config.JumpPower; h:SetAttribute("ConfiguredWalkSpeed",Config.WalkSpeed); h:SetAttribute("ConfiguredJumpPower",Config.JumpPower); h:SetAttribute("StandingHipHeight",h.HipHeight); h:SetAttribute("Crouched",false); self.States:Register(player,h); table.insert(self.Connections[player],h.Died:Connect(function() local cancel:(Player,string)->()=self.OnCancel; cancel(player,"Death"); self.States:MarkDead(player); self.Remote:FireClient(player,"Died") end)); self.Remote:FireClient(player,"Spawned",character) end
function Service._player(self:any,player:Player) self.Connections[player]={}; table.insert(self.Connections[player],player.CharacterAdded:Connect(function(c) self:_character(player,c) end)); table.insert(self.Connections[player],player.CharacterRemoving:Connect(function() local cancel:(Player,string)->()=self.OnCancel; cancel(player,"CharacterRemoved"); self.States:CancelAll(player,"Dead"); self.BoundCharacters[player]=nil; self.Remote:FireClient(player,"Removed") end)); if player.Character then task.spawn(function() self:_character(player,player.Character :: Model) end) end end
function Service.Start(self:any) Players.PlayerAdded:Connect(function(p) self:_player(p) end); Players.PlayerRemoving:Connect(function(p) for _,c:RBXScriptConnection in self.Connections[p] or {} do c:Disconnect() end; self.Connections[p]=nil; self.BoundCharacters[p]=nil end); for _,p in Players:GetPlayers() do self:_player(p) end end
return Service
