--!strict
-- LocalScript: StarterPlayer/StarterPlayerScripts/ClientMain (the player framework's only bootstrap)
local controllers=script.Parent:WaitForChild("Controllers")
local FirstPerson=require(controllers:WaitForChild("FirstPersonController"))
local Camera=require(controllers:WaitForChild("CameraController")).new()
local LookPoseReplication=require(controllers:WaitForChild("LookPoseReplicationController"))
local Animation=require(controllers:WaitForChild("CharacterAnimationController")).new()
local Footsteps=require(controllers:WaitForChild("FootstepController")).new()
local Viewmodel=require(controllers:WaitForChild("ViewmodelController")).new()
FirstPerson:Start(); Camera:Start(); LookPoseReplication:Start(); Animation:Start(); Footsteps:Start()
require(controllers:WaitForChild("InputController")).Start(FirstPerson)
require(controllers:WaitForChild("InteractionController")).new(Animation,Camera):Start()
require(controllers:WaitForChild("CutsceneController")).new(Camera,Animation):Start()
Viewmodel:Start()
