--!strict
-- LocalScript: StarterPlayer/StarterPlayerScripts/ClientMain (the player framework's only bootstrap)
local controllers=script.Parent:WaitForChild("Controllers")
local FirstPerson=require(controllers:WaitForChild("FirstPersonController"))
local Camera=require(controllers:WaitForChild("CameraController")).new()
local LookPoseReplication=require(controllers:WaitForChild("LookPoseReplicationController"))
local Animation=require(controllers:WaitForChild("CharacterAnimationController")).new()
local Footsteps=require(controllers:WaitForChild("FootstepController")).new()
local CharacterSounds=require(controllers:WaitForChild("CharacterSoundController")).new()
local Viewmodel=require(controllers:WaitForChild("ViewmodelController")).new(Camera,FirstPerson)
local Tools=require(controllers:WaitForChild("ToolController")).new(Animation,Viewmodel)
FirstPerson:Start(); Camera:Start(); LookPoseReplication:Start(); Animation:Start(); Footsteps:Start(); CharacterSounds:Start(); Viewmodel:Start(); Tools:Start()
require(controllers:WaitForChild("InputController")).Start(FirstPerson)
local Hiding=require(controllers:WaitForChild("HidingController")).new(Camera,Animation,FirstPerson); Hiding:Start()
require(controllers:WaitForChild("InteractionController")).new(Animation,Camera,Hiding):Start()
require(controllers:WaitForChild("CutsceneController")).new(Camera,Animation):Start()
require(controllers:WaitForChild("EntityEffectsController")).new(Camera):Start()
