--!strict
-- ModuleScript: StarterPlayer/StarterPlayerScripts/Controllers/FootstepController
local Players=game:GetService("Players"); local RS=game:GetService("ReplicatedStorage"); local ContentProvider=game:GetService("ContentProvider"); local SoundService=game:GetService("SoundService"); local RunService=game:GetService("RunService")
local Config:any=require(RS:WaitForChild("Shared"):WaitForChild("FootstepConfig")); local C={}; C.__index=C
local LocalPlayer=Players.LocalPlayer :: Player
function C.new():any return setmetatable({Characters={},SoundCache={},LastStep={} :: {[Model]:number},LastMarker={} :: {[Model]:number},NextFallback={} :: {[Model]:number},FallbackAccumulator=0,ObservedTracks=setmetatable({}, {__mode="k"})},C) end
function C._sound(self:any,parent:BasePart,id:string,volumeMultiplier:number,pitchMultiplier:number)
	if id=="" or id=="rbxassetid://0" then return end
	local entry:any=self.SoundCache[id]
	if not entry then local created=Instance.new("Sound"); created.SoundId=id; created.RollOffMaxDistance=Config.MaxDistance; created.RollOffMinDistance=4; created.RollOffMode=Enum.RollOffMode.InverseTapered; created.Parent=SoundService; entry={Sounds={created},Next=1}; self.SoundCache[id]=entry end
	local sounds:{Sound}=entry.Sounds; local slot:number=entry.Next
	if not sounds[slot] then local clone=sounds[1]:Clone(); clone.Parent=SoundService; sounds[slot]=clone end
	local sound:Sound=sounds[slot]; entry.Next=slot%Config.VoicesPerSound+1
	-- Never queue Play on an unloaded sound: Roblox would play that old contact one
	-- or two seconds later, after the player has already changed surfaces.
	if not sound.IsLoaded then return end
	sound:Stop(); sound.TimePosition=0; sound.Parent=parent; sound.Volume=Config.Volume*volumeMultiplier; sound.PlaybackSpeed=Random.new():NextNumber(Config.PitchMin,Config.PitchMax)*pitchMultiplier; sound:Play()
end
function C._step(self:any,character:Model,kind:string,foot:string?) local now=os.clock(); if kind~="Land" and now-(self.LastStep[character] or 0)<Config.MinimumStepInterval then return end; self.LastStep[character]=now; if kind~="Land" then self.NextFallback[character]=now+(Config.FallbackIntervals[kind] or Config.FallbackIntervals.Walk) end; local root=character:FindFirstChild("HumanoidRootPart"); local h=character:FindFirstChildOfClass("Humanoid"); if not root or not root:IsA("BasePart") or not h or h.FloorMaterial==Enum.Material.Air then return end; local localCharacter=LocalPlayer.Character; local localRoot=if localCharacter then localCharacter:FindFirstChild("HumanoidRootPart") else nil; if character~=localCharacter and localRoot and localRoot:IsA("BasePart") and (localRoot.Position-root.Position).Magnitude>Config.MaxDistance then return end; local velocity=Vector3.new(root.AssemblyLinearVelocity.X,0,root.AssemblyLinearVelocity.Z).Magnitude; if kind~="Land" and velocity<Config.MinHorizontalSpeed then return end; local originPart=character:FindFirstChild(if foot=="Left" then "LeftFoot" elseif foot=="Right" then "RightFoot" else "HumanoidRootPart"); local origin=if originPart and originPart:IsA("BasePart") then originPart.Position else root.Position; local params=RaycastParams.new(); params.FilterType=Enum.RaycastFilterType.Exclude; params.FilterDescendantsInstances={character}; local hit=workspace:Raycast(origin,Vector3.new(0,-Config.RayLength,0),params); if not hit then return end; local cursor:Instance?=hit.Instance; local override:any=nil; while cursor and cursor~=workspace do override=cursor:GetAttribute("SurfaceProfile"); if typeof(override)=="string" then break end; cursor=cursor.Parent end; local profile=if typeof(override)=="string" and Config.Profiles[override] then override else Config.MaterialProfiles[hit.Material.Name] or "Default"; local definition=Config.Profiles[profile]; local sounds=definition[kind] or definition.Walk; if Config.Debug then print(`[Footstep] {character.Name} {kind} {hit.Material.Name} -> {profile}`) end; if #sounds>0 then self:_sound((originPart :: BasePart?) or root,sounds[math.random(1,#sounds)],definition.VolumeMultiplier,definition.PitchMultiplier) end end
function C._observe(self:any,character:Model) if self.Characters[character] then return end; local bucket:{RBXScriptConnection}={}; self.Characters[character]=bucket; local h=character:WaitForChild("Humanoid",5); if not h or not h:IsA("Humanoid") then return end; local animator=h:WaitForChild("Animator",5); if not animator or not animator:IsA("Animator") then return end; local function track(t:AnimationTrack) if self.ObservedTracks[t] then return end; self.ObservedTracks[t]=true; local names=if Config.MarkerStyle=="Separate" then {"FootstepLeft","FootstepRight"} else {"Footstep"}; for _,name in names do table.insert(bucket,t:GetMarkerReachedSignal(name):Connect(function(value) if not t.IsPlaying or t.WeightCurrent<.15 then return end; self.LastMarker[character]=os.clock(); local trackName=t.Name; local kind=if string.sub(trackName,1,10)=="CrouchWalk" then "Crouch" elseif string.sub(trackName,1,3)=="Run" then "Run" else "Walk"; self:_step(character,kind,if name=="Footstep" then value elseif name=="FootstepLeft" then "Left" else "Right") end)) end end; table.insert(bucket,animator.AnimationPlayed:Connect(track)); for _,t in animator:GetPlayingAnimationTracks() do track(t) end; table.insert(bucket,h.StateChanged:Connect(function(old,new) if old==Enum.HumanoidStateType.Freefall and new==Enum.HumanoidStateType.Landed then self:_step(character,"Land") end end)); character.Destroying:Once(function() for _,connection in bucket do connection:Disconnect() end; self.Characters[character]=nil; self.LastStep[character]=nil; self.LastMarker[character]=nil; self.NextFallback[character]=nil end) end

function C._fallback(self:any,dt:number) if not Config.MarkerFallbackEnabled then return end; self.FallbackAccumulator+=dt; if self.FallbackAccumulator<Config.FallbackUpdateInterval then return end; self.FallbackAccumulator=0; local now=os.clock(); for character in self.Characters do local root=character:FindFirstChild("HumanoidRootPart"); local humanoid=character:FindFirstChildOfClass("Humanoid"); if root and root:IsA("BasePart") and humanoid and humanoid.Health>0 and humanoid.FloorMaterial~=Enum.Material.Air then local speed=Vector3.new(root.AssemblyLinearVelocity.X,0,root.AssemblyLinearVelocity.Z).Magnitude; if speed>=Config.MinHorizontalSpeed then local lastMarker=self.LastMarker[character]; if lastMarker and now-lastMarker<Config.MarkerFallbackSilenceTimeout then self.NextFallback[character]=now; continue end; local kind=if humanoid:GetAttribute("Crouched")==true then "Crouch" elseif speed>13 then "Run" else "Walk"; if now>=(self.NextFallback[character] or 0) then self:_step(character,kind,nil) end else self.NextFallback[character]=now end end end end
function C._preload(self:any) local assets:{Instance}={}; for _,definition:any in Config.Profiles do for _,kind in {"Walk","Run","Crouch","Land"} do for _,id in definition[kind] do if id~="" and id~="rbxassetid://0" and not self.SoundCache[id] and #assets<Config.MaximumPreloadedSounds then local sound=Instance.new("Sound"); sound.SoundId=id; sound.RollOffMaxDistance=Config.MaxDistance; sound.RollOffMinDistance=4; sound.RollOffMode=Enum.RollOffMode.InverseTapered; sound.Parent=SoundService; self.SoundCache[id]={Sounds={sound},Next=1}; table.insert(assets,sound) end end end end; task.spawn(function() for startIndex=1,#assets,Config.PreloadBatchSize do local batch:{Instance}={}; for index=startIndex,math.min(#assets,startIndex+Config.PreloadBatchSize-1) do table.insert(batch,assets[index]) end; pcall(function() ContentProvider:PreloadAsync(batch) end); task.wait() end end) end
function C.Start(self:any) self:_preload(); RunService.Heartbeat:Connect(function(dt) self:_fallback(dt) end); local function player(p:Player) p.CharacterAdded:Connect(function(c) self:_observe(c) end); if p.Character then self:_observe(p.Character) end end; Players.PlayerAdded:Connect(player); for _,p in Players:GetPlayers() do player(p) end end
return C
