--!strict
-- ModuleScript: StarterPlayer/StarterPlayerScripts/Controllers/InteractionController
local CAS=game:GetService("ContextActionService"); local CS=game:GetService("CollectionService"); local Players=game:GetService("Players"); local RunService=game:GetService("RunService"); local RS=game:GetService("ReplicatedStorage")
local Config:any=require(RS:WaitForChild("Shared"):WaitForChild("InteractionConfig")); local C={}; C.__index=C
local LocalPlayer=Players.LocalPlayer :: Player
local Remotes=RS:WaitForChild("Remotes")
function C.new(animation:any,camera:any,hiding:any?):any return setmetatable({Animation=animation,Camera=camera,Hiding=hiding,Target=nil,Busy=false,Prompt=nil,HoldSerial=0,Remote=Remotes:WaitForChild("InteractionStateChanged") :: RemoteEvent,Request=Remotes:WaitForChild("InteractionRequest") :: RemoteEvent},C) end
function C._gui(self:any) local gui=Instance.new("ScreenGui"); gui.Name="InteractionGui"; gui.ResetOnSpawn=false; gui.Parent=LocalPlayer:WaitForChild("PlayerGui"); local label=Instance.new("TextLabel"); label.Name="Prompt"; label.AnchorPoint=Vector2.new(.5,.5); label.Position=UDim2.fromScale(.5,.62); label.Size=UDim2.fromOffset(360,44); label.BackgroundTransparency=1; label.TextColor3=Color3.new(1,1,1); label.TextStrokeTransparency=.4; label.TextScaled=true; label.Visible=false; label.Parent=gui; self.Prompt=label end
function C._scan(self:any) if self.Busy then return end; local camera=workspace.CurrentCamera; if not camera then return end; local ray=camera:ViewportPointToRay(camera.ViewportSize.X/2,camera.ViewportSize.Y/2); local params=RaycastParams.new(); params.FilterType=Enum.RaycastFilterType.Exclude; local character=LocalPlayer.Character; params.FilterDescendantsInstances=if character then {character} else {}; local hit=workspace:Raycast(ray.Origin,ray.Direction*Config.ScanDistance,params); local cursor:Instance?=if hit then hit.Instance else nil; local found:Instance?=nil; while cursor and cursor~=workspace do if CS:HasTag(cursor,"Interactable") then found=cursor; break end; cursor=cursor.Parent end; local foundId=if found then found:GetAttribute("InteractionId") else nil; if found and foundId~="PickupTool" and found:FindFirstChildWhichIsA("ProximityPrompt",true) then found=nil; foundId=nil end; self.Target=found; self.Prompt.Visible=found~=nil; if found then local hold=found:GetAttribute("HoldDuration"); local text=found:GetAttribute("InteractionText"); local keyText=if foundId=="PickupTool" then "F" else "E"; self.Prompt.Text=(if typeof(hold)=="number" and hold>0 then "Hold "..keyText.." to " else "Press "..keyText.." to ")..(if typeof(text)=="string" then text else "Interact") end end
function C._input(self:any,actionName:string,state:Enum.UserInputState):Enum.ContextActionResult
	if state==Enum.UserInputState.End or state==Enum.UserInputState.Cancel then self.HoldSerial=(self.HoldSerial :: number)+1; return Enum.ContextActionResult.Sink end
	if state~=Enum.UserInputState.Begin or self.Busy then return Enum.ContextActionResult.Pass end
	if self.Hiding and self.Hiding:HandleInteract() then return Enum.ContextActionResult.Sink end
	local target:Instance?=self.Target; if not target then return Enum.ContextActionResult.Pass end
	local id=target:GetAttribute("InteractionId")
	if actionName=="HorrorPickup" and id~="PickupTool" then return Enum.ContextActionResult.Pass end
	if actionName=="HorrorInteract" and id=="PickupTool" then return Enum.ContextActionResult.Pass end
	local rawDuration=target:GetAttribute("HoldDuration"); local duration=if typeof(rawDuration)=="number" then math.max(0,rawDuration) else 0
	self.HoldSerial=(self.HoldSerial :: number)+1; local serial:number=self.HoldSerial
	if duration<=0 then self.Request:FireServer(target,id) else task.delay(duration,function() if self.HoldSerial==serial and self.Target==target and not self.Busy then self.Request:FireServer(target,id) end end) end
	return Enum.ContextActionResult.Sink
end
function C.Start(self:any) self:_gui(); CAS:BindAction("HorrorInteract",function(actionName:string,state:Enum.UserInputState,_inputObject:InputObject) return self:_input(actionName,state) end,true,Enum.KeyCode.E,Enum.KeyCode.ButtonX); CAS:SetTitle("HorrorInteract","Interact"); CAS:BindAction("HorrorPickup",function(actionName:string,state:Enum.UserInputState,_inputObject:InputObject) return self:_input(actionName,state) end,true,Enum.KeyCode.F); CAS:SetTitle("HorrorPickup","Pick up"); RunService.RenderStepped:Connect(function() self:_scan() end); self.Remote.OnClientEvent:Connect(function(msg:any) if msg.kind=="Started" then self.Busy=true; self.Prompt.Visible=false; if msg.animationKey then self.Animation:PlayInteractionAction(msg.animationKey,msg.startTime,msg.duration) end; local cameraPointValue:any=msg.cameraPoint; if typeof(cameraPointValue)=="Instance" then local cameraPoint:Instance=cameraPointValue :: Instance; if cameraPoint:IsA("Attachment") and self.Camera:Acquire("Interaction","Interaction") then self.Camera:SetScriptCFrame("Interaction",cameraPoint.WorldCFrame) end end elseif msg.kind=="Completed" or msg.kind=="Cancelled" or msg.kind=="Rejected" then self.Busy=false; self.Animation:StopInteractionAction(.12); self.Camera:Release("Interaction") end end) end
return C
